### ISSUE TITLE
Object of class UnwindExit could not be converted to string

### ISSUE THREAD

**Issue by arwin009** [samayo/bulletproof#135]
After upgrading PHP version to 8.1, I am getting this error when trying instantiate the Bulletproof Image class:

```
Warning: Uncaught Error: Object of class UnwindExit could not be converted to string in /project/vendor/samayo/bulletproof/src/bulletproof.php:16
Stack trace:
#0 /project/vendor/composer/ClassLoader.php(571): include()
#1 /project/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/project/...')
#2 /project/app/CommonModule/model/Product.php(557): Composer\Autoload\ClassLoader->loadClass('Bulletproof\\Ima...')
  thrown in /project/vendor/samayo/bulletproof/src/bulletproof.php on line 16

Fatal error: During inheritance of ArrayAccess: Uncaught  in /project/vendor/samayo/bulletproof/src/bulletproof.php on line 16
```

I am using latest Bulletproof version:
samayo/bulletproof                  v4.0.1

What could be wrong? Is there a support for PHP 8.1?

**Comment by samayo** [comment]
Hello, I will make some updates this weekend

**Comment by arwin009** [comment]
Thank you!

**Comment by samayo** [comment]
I guess it should work now, sorry for the delay. 
I have tested it with PHP8.1 and it works
